server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ticket-service
          uri:
            lb://ticket-service
          predicates:
            - Path=/api/v1/tickets