server:
  port: 8100

spring:
  data:
    mongodb:
#      user: root
#      password: root
#      uri: mongodb://localhost:27017/ticketoffice
#      authentication-database: admin
      database: ticketoffice
      port: 27017
      host: localhost
#      auto-index-creation: true